services:
  backend:
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads

  frontend:
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
